
export const urduTranslationMap: { [key: string]: string } = {
  'raiwind': 'رائے ونڈ',
  'changa manga': 'چھانگا مانگا',
  'kot radha kishan': 'کوٹ رادہاکشن',
  'manga mandi': 'مانگا منڈی',
  'raiwind city': 'رائے ونڈ سٹی',
  'along with': 'ہمراہ',
  'kasur': 'قصور',
  'lahore': 'لاہور',
  'pattoki': 'پتونکی',
  'chunian': 'چونیاں',
  'phool nagar': 'پھول نگر',
  'habibabad': 'حبیب آباد',
  'mustafabad': 'مصطفی آباد',
  'ellahabad': 'الہٰ آباد',
  'kanganpur': 'کنگن پور',
  'khudian': 'کھڈیاں',
  'bhai pheru': 'بھائی پھیرو',
  'lalyani': 'للیانی',
  'okara': 'اوکاڑہ',
  'sahiwal': 'ساہیوال',
  'sheikhupura': 'شیخوپورہ',
  'gujranwala': 'گوجرانوالہ',
  's/o': 'ولد',
  'son of': 'ولد',
  'd/o': 'بنت',
  'daughter of': 'بنت',
  'w/o': 'زوجہ',
  'wife of': 'زوجہ',
  'p/o': 'حال قابض',
  'p.o': 'حال قابض',
  'present occupier': 'حال قابض',
  'r/o': 'سکنہ',
  'resident of': 'سکنہ',
  'tehsil': 'تحصیل',
  'district': 'ضلع',
  'road': 'روڈ',
  'mohallah': 'محلہ',
  'chak': 'چک',
  'kot': 'کوٹ',
  'house': 'مکان',
  'street': 'گلی',
  'gali': 'گلی',
  'near': 'نزد',
  'opposite': 'بالمقابل',
  'main bazar': 'مین بازار',
  'bazar': 'بازار',
  'village': 'گاوں',
  'dhariwal': 'دھاریوال',
  'jamber': 'جمبر',
  'shiekh hussain': 'شیخ حسین',
  'behlolpur': 'بہلول پور',
  'assistant manager (operation)': 'اِسسٹنٹ مینیجر (آپریشن)',
  'm&s team': 'ایم اینڈ ایس ٹیم',
  'engr.': 'انجینئر',
  'engr': 'انجینئر',
  'sub divisional checking team': 'سب ڈویژنل چیکنگ ٹیم',
  'inyat ullah': 'عنایت اللہ',
  'inayat ullah': 'عنایت اللہ',
  'nia moh': 'نیاز محمد',
  'noor muhammad': 'نور محمد',
  'naseem shah': 'نسیم شاہ',
  'black': 'سیاہ',
  'meter': 'میٹر',
  'ft': 'فٹ',
  'foot': 'فٹ',
  'feet': 'فٹ',
  'meters': 'میٹر',
  'ls': 'ایل ایس',
  'lm': 'ایل ایم',
  'alm': 'اے ایل ایم',
  'bd': 'بل ڈسٹری بیوٹر',
  'ms': 'ایم ایس',
  'm/r': 'میٹر ریڈر',
  'je': 'جے ای',
  'sdo': 'سب ڈویژنل آفیسر',
  'acting meter inspector': 'ایکٹنگ میٹر انسپکٹر',
  'Direct Supply From LESCO main Cable': 'لیسکو کی مین کیبل سے ڈائریکٹ سپلائی لگا رکھی تھی، جس کے ذریعے غیر قانونی طور پر بجلی استعمال/چوری کی جا رہی تھی',
  'Direct Supply From L.T line': 'ایل ٹی لائن سے ڈائریکٹ سپلائی لگا رکھی تھی، جس کے ذریعے غیر قانونی طور پر بجلی استعمال/چوری کی جا رہی تھی',
  'Direct Supply From Meter terminal.': 'میٹر ٹرمینل بلاک سے ڈائریکٹ سپلائی لگا رکھی تھی، جس کے ذریعے غیر قانونی طور پر بجلی استعمال/چوری کی جا رہی تھی',
  'Meter Body Tempered.': 'میٹرباڈی ٹیمپرڈ کرکے بجلی چوری کر رہا تھا۔',
  'Meter Body Tempered': 'میٹرباڈی ٹیمپرڈ کرکے بجلی چوری کر رہا تھا۔',
  'Hole In Meter Body. Meter Reversed.': 'میٹرباڈی میں سوراخ کرکے میٹر ریورس کر رکھا تھا',
  'Hole in Meter Terminal Block.': 'میٹر ٹرمینل بلاک میں سوراخ کرکے بجلی چوری کر رہا تھا',
  'Scratches on Figures. Meter Reversed.': 'میٹر ریورس کر رکھا تھا۔ موقع پر چیک کرنے سے میٹر کے فگرز پر واضح نشانات پائے گئے، جس کی وجہ سے بجلی چوری کی جا رہی تھی',
  'Shunt In Terminal Block.': 'میٹر ٹرمینل بلاک میں شنٹ لگا کر میٹر سلو کر رکھا تھا',
  'One Phase Dead Stop. Meter 33% Slow.': 'ایک فیز مردہ ہے، میٹر 33 فیصد سلو ہے',
  'Two Phase Dead Stop. Meter 66% Slow.': 'دو فیز مردہ ہیں، میٹر 66 فیصد سلو ہے',
  'Meter Dead Stop.': 'میٹر مکمل طور پر بند ہے (ڈیڈ سٹاپ)',
  'Meter Intensionally Display Wash.': 'میٹر کا ڈسپلے جان بوجھ کر واش/خراب کر رکھا تھا، جس کے باعث بجلی کی غیر قانونی ترسیل و استعمال جاری تھا',
  'Meter Intensionally Burnt.': 'میٹر کو جان بوجھ کر جلا دیا تھا، جس کے باعث بجلی کی غیر قانونی ترسیل و استعمال جاری تھا',
  'ls-i': 'ایل ایس ون',
  'ls-ii': 'ایل ایس ٹو',
  'lm-i': 'ایل ایم ون',
  'lm-ii': 'ایل ایم ٹو',
  'ms-i': 'ایم ایس ون',
  'ms-ii': 'ایم ایس ٹو',
  'lorry driver': 'لاری ڈرائیور',
  'laeeque ahmad': 'لئیق احمد',
  'amjad ali': 'امجد علی',
  'muhammad afzal.': 'محمد افضل۔',
  'muhammad amin': 'محمد امین',
  'pervaiz akhtar': 'پرویز اختر',
  'mumtaz ali': 'ممتاز علی',
  'muhammad ashraf': 'محمد اشرف',
  'muhammad fazal': 'محمد فضل',
  'javaid iqbal': 'جاوید اقبال',
  'anjum maqsood': 'انجم مقصود',
  'ghulam muhammad': 'غلام محمد',
  'jameel ahmad': 'جمیل احمد',
  'zulifqar ali bhatti': 'ذوالفقار علی بھٹی',
  'nazeer ahmad': 'نذیر احمد',
  'muhammad azam': 'محمد اعظم',
  'tahir hussain': 'طاہر حسین',
  'muhammad sarwar': 'محمد سرور',
  'muhammad imran': 'محمد عمران',
  'muhammad shafique': 'محمد شفیق',
  'irfan ali ayoub': 'عرفان علی ایوب',
  'muhammad yaqoob': 'محمد یعقوب',
  'muhammad asif': 'محمد آصف',
  'kashif mehmood': 'کاشف محمود',
  'ch.bilal ahmad': 'چوہدری بلال احمد',
  'zia-ul-qamar': 'ضیاء القمر',
  'muhammad dawood': 'محمد داؤد',
  'muhammad tariq mahmood': 'محمد طارق محمود',
  'shehzad anjum': 'شہزاد انجم',
  'shahbaz ali': 'شہباز علی',
  'muhammad amir': 'محمد عامر',
  'muhammad amjad': 'محمد امجد',
  'muhammad rasheed': 'محمد رشید',
  'mohammad asghar': 'محمد اصغر',
  'nadeem sajjad': 'ندیم سجاد',
  'naeem ahmad': 'نعیم احمد',
  'muhammad usman': 'محمد عثمان',
  'muhammad mubeen': 'محمد مبین',
  'shahbaz ahmad saqi': 'شہباز احمد ساقی',
  'mohsan bashir': 'محسن بشیر',
  'ch; muhammad shafqat khan': 'چوہدری; محمد شفقت خان',
  'muhammad shakeel': 'محمد شکیل',
  'ali shan': 'علی شان',
  'shafqat ali babar': 'شفقت علی بابر',
  'mohammad asif': 'محمد آصف',
  'waseem akram': 'وسیم اکرم',
  'muhammad riaz': 'محمد ریاض',
  'kazim ali': 'کاظم علی',
  'asjad ali': 'اسجد علی',
  'attaullah khattak': 'عطا اللہ خٹک',
  'tahir islam': 'طاہر اسلام',
  'imran nasir': 'عمران ناصر',
  'muhammad aslam': 'محمد اسلم',
  'muhammad farman': 'محمد فرمان',
  'dildar hussain': 'دلدار حسین',
  'tallat mehmood': 'طلعت محمود',
  'allah ditta': 'اللہ دتہ',
  'saeed ahmed': 'سعید احمد',
  'shakeel ahmad': 'شکیل احمد',
  'mohammad amjad': 'محمد امجد',
  'maqbool ahmed': 'مقبول احمد',
  'mohammad asif bashir': 'محمد آصف بشیر',
  'abdul latif': 'عبداللطیف',
  'shafaqat ali sajid': 'شفقت علی ساجد',
  'maqgood ahmad': 'مقبول احمد',
  'muhammad maqbool': 'محمد مقبول',
  'nasrullah khan': 'نصراللہ خان',
  'muhammad saleem': 'محمد سلیم',
  'iftikhar ahmad': 'افتخار احمد',
  'irfan haider': 'عرفان حیدر',
  'zulifqar ali': 'ذوالفقار علی',
  'muhammad abbas': 'محمد عباس',
  'muhammad nawaz': 'محمد نواز',
  'mohammad arshad': 'محمد ارشد',
  'abid hussain': 'عابد حسین',
  'shahzad nadeem': 'شہزاد ندیم',
  'muhammad ashfaq': 'محمد اشفاق',
  'shahbaz ahmed': 'شہباز احمد',
  'shoaib akhtar': 'شعیب اختر',
  'mirza muhammad abid baig': 'مرزا محمد عابد بیگ',
  'muhammad dilshad': 'محمد دلشاد',
  'naseem akbar': 'نسیم اکبر',
  'zulfqar ali': 'ذوالفقار علی',
  'naveed shehzad hussain': 'نوید شہزاد حسین',
  'muhammad irfan': 'محمد عرفان',
  'danish masih': 'دانش مسیح',
  'sajjad masih': 'سجاد مسیح',
  'junaid jamil': 'جنید جمیل',
  'abdul rasheed': 'عبدالرشید',
  'fiaz ullah athar': 'فیاض اللہ اطہر',
  'muhammad saddique': 'محمد صدیق',
  'imarat ali': 'امارت علی',
  'muhammad sharif': 'محمد شریف',
  'akhtar hussain': 'اختر حسین',
  'muhammad shahbaz price': 'محمد شہباز قیمت',
  'shakeel lal': 'شکیل لال',
  'muhammad latif': 'محمد لطیف',
  'amir allah wasaya': 'امیر اللہ وسایا',
  'muhammad farooq': 'محمد فاروق',
  'faryad ali': 'فریاد علی',
  'hanan ashraf': 'حنان اشرف',
  'farman arshad': 'فرمان ارشد',
  'm.naveed': 'ایم نوید',
  'faisal masood': 'فیصل مسعود',
  'maqsood ahmad': 'مقصود احمد',
  'safdar malik': 'صفدر ملک',
  'salman m.r': 'سلمان ایم آر',
  'muhammadmurtaza': 'محمد مرتضیٰ',
  'muhammad aqeel': 'محمد عقیل',
  'muhammad asghar': 'محمد اصغر',
  'muhammad salman': 'محمد سلمان',
  'awaise munir': 'اویس منیر',
  'ghulam murtaza': 'غلام مرتضیٰ',
  'zaeem sabir': 'زعیم صابر',
  'mudassar yaseen': 'مدثر یاسین',
  'muhammad khaliq': 'محمد خالق',
  'muhammad naveed sharif': 'محمد نوید شریف',
  'qaisar nadeem': 'قیصر ندیم',
  'rozdar khan': 'روزدار خان',
  'zahid naseer': 'زاہد نصیر',
  'khizar hayat': 'خضر حیات',
  'saeed ahmad': 'سعید احمد',
  'shehzad qaisar': 'شہزاد قیصر',
  'ch. muhammad abubakar siddique': 'چوہدری محمد ابوبکر صدیق',
  'muhammad umar': 'محمد عمر',
  'muhammad younas': 'محمد یونس',
  'ahmad naseem': 'احمد نسیم',
  'tauqeer ali shahzad': 'توقیر علی شہزاد',
  'muhammad ramzan': 'محمد رمضان',
  'm. imran rafique': 'ایم عمران رفیق',
  'imran khan': 'عمران خان',
  'adil usman': 'عادل عثمان',
  'adil hussain': 'عادل حسین',
  'sajid javed': 'ساجد جاوید',
  'kashif hussain': 'کاشف حسین',
  'mudassar sehar': 'مدثر سحر',
  'abdul khaliq': 'عبدالخالق',
  'sakhawat ali khan': 'سخاوت علی خان',
  'kalim ullah': 'کلیم اللہ',
  'atif mahmood': 'عاطف محمود',
  'muhammad umar subhani': 'محمد عمر سبحانی۔',
  'shan ali': 'شان علی',
  'bhola masih': 'بھولا مسیح',
  'muhammad': 'محمد',
  'fiaz': 'فیاض',
  'ahmed': 'احمد',
  'ahmad': 'احمد',
  'ali': 'علی',
  'hussain': 'حسین',
  'raza': 'رضا',
  'hassan': 'حسن',
  'khalid': 'خالد',
  'tariq': 'طارق',
  'naveed': 'نوید',
  'shahid': 'شاہد',
  'zafar': 'ظفر',
  'iqbal': 'اقبال',
  'anwar': 'انور',
  'bashir': 'بشیر',
  'munir': 'منیر',
  'rashid': 'رشید',
  'sultan': 'سلطان',
  'shaukat': 'شوکت',
  'rafiq': 'رفیق',
  'farooq': 'فاروق',
  'siddique': 'صدیق',
  'tayyab': 'طیب',
  'zubair': 'زبیر',
  'bilal': 'بلال',
  'hamza': 'حمزہ',
  'usman': 'عثمان',
  'umar': 'عمر',
  'abu bakar': 'ابوبکر',
  'abubakar': 'ابوبکر',
  'mian': 'میاں',
  'syed': 'سید',
  'haji': 'حاجی',
  'ch.': 'چوہدری',
  'ch': 'چوہدری',
  'malik': 'ملک',
  'sheikh': 'شیخ',
  'sh.': 'شیخ',
  'sh': 'شیخ',
  'bhatti': 'بھٹی',
  'jatt': 'جٹ',
  'rajpoot': 'راجپوت',
  'rana': 'رانا',
  'dogar': 'ڈوگر',
  'arain': 'آرائیں',
  'guijar': 'گجر',
  'gujjar': 'گجر',
  'butt': 'بٹ',
  'mirza': 'مرزا',
  'beg': 'بیگ',
  'baig': 'بیگ',
  'kamran': 'کامران',
  'rizwan': 'رضوان',
  'adnan': 'عدنان',
  'faisal': 'فیصل',
  'irfan': 'عرفان',
  'sajid': 'ساجد',
  'majid': 'ماجد',
  'zahoor': 'ظہور',
  'akmal': 'اکمل',
  'aslam': 'اسلم',
  'akram': 'اکرم',
  'arshad': 'ارشد',
  'ashfaq': 'اشفاق',
  'ashraf': 'اشرف',
  'asif': 'آصف',
  'azam': 'اعظم',
  'babur': 'بابر',
  'babar': 'بابر',
  'habib': 'حبیب',
  'haider': 'حیدر',
  'hameed': 'حمید',
  'ibrahim': 'ابراہیم',
  'idrees': 'ادریس',
  'ilyas': 'الیاس',
  'imran': 'عمران',
  'ishfaq': 'اشفاق',
  'ishaq': 'اسحاق',
  'ismail': 'اسماعیل',
  'imtiaz': 'امتیاز',
  'javaid': 'جاوید',
  'javed': 'جاوید',
  'latif': 'لطیف',
  'liaquat': 'لیاقت',
  'maqsood': 'مقصود',
  'masood': 'مسعود',
  'mubarak': 'مبارک',
  'mubashir': 'مبشر',
  'muddasar': 'مدثر',
  'mudassar': 'مدثر',
  'mujtaba': 'مجتبیٰ',
  'mustafa': 'مصطفی',
  'nadeem': 'ندیم',
  'naseer': 'نصیر',
  'nasir': 'ناصر',
  'nawaz': 'نواز',
  'qasim': 'قاسم',
  'qayyum': 'قیوم',
  'rafeeq': 'رفیق',
  'rehan': 'ریحان',
  'saif': 'سیف',
  'saleem': 'سلیم',
  'salman': 'سلمان',
  'shabbir': 'شبیر',
  'shahzad': 'شہزاد',
  'shakeel': 'شکیل',
  'sharif': 'شریف',
  'tahir': 'طاہر',
  'waheed': 'وحید',
  'waqas': 'وقاص',
  'yaseen': 'یاسین',
  'younas': 'یونس',
  'yousaf': 'یوسف',
  'zaheer': 'ظہیر',
  'shoaib': 'شعیب',
  'tauseef': 'توصیف',
  'tanveer': 'تنویر',
  'khurram': 'خرم',
  'shehzad': 'شہزاد',
  'aftab': 'آفتاب',
  'mahtab': 'مہتاب',
  'khurshid': 'خورشید',
  'pervaiz': 'پرویز',
  'akhtar': 'اختر',
  'asghar': 'اصغر',
  'akbar': 'اکبر',
  'mohammad': 'محمد',
  'muhamad': 'محمد',
  'muhammd': 'محمد',
  'm.': 'ایم',
  'afzal': 'افضل',
  'inayat': 'عنایت',
  'ullah': 'اللہ',
  'inayatullah': 'عنایت اللہ'
};

export const translateToUrdu = (text: string | undefined): string => {
  if (!text) return '۔۔۔۔۔۔۔۔۔۔۔۔';
  let translated = text;

  // Sort keys by length descending to handle longer terms first (e.g. 'raiwind city' before 'raiwind')
  const sortedKeys = Object.keys(urduTranslationMap).sort((a, b) => b.length - a.length);

  sortedKeys.forEach(key => {
    // Use string replace instead of word boundary regex to handle mixed scripts better
    translated = translated.split(new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi')).join(urduTranslationMap[key]);
  });

  return translated;
};
